### ISSUE TITLE
Sanboxed Isolation

### ISSUE THREAD

**Issue by rexkenley** [rexm/Handlebars.Net#284]
Hi

Can HandleBars.net be used in a Crm365 Sandboxed isolation environment?
https://crmbusiness.wordpress.com/2015/02/05/understanding-plugin-sandbox-mode/

Thanks!

**Comment by rexm** [comment]
Try it and let us know :)

**Comment by rexkenley** [comment]
It is complaining about not being able to load a file. But it doesn't say which one. Although I do know that there are some .net 4.5.2 dlls that have trouble with being sandboxed (System.Net Smtp for example)

*Ps Hello fellow King.

**Comment by rexm** [comment]
Closing this due to inactivity.

**Comment by janis-veinbergs** [comment]
Handlebars.Net.Helpers cannot be used as it wants to retrieve current working directory.

Handlebars.Net itself also doesn't work and throws:
```
System.TypeInitializationException: The type initializer for 'HandlebarsDotNet.Features.BuildInHelpersFeature' threw an exception. ---&gt; System.Security.VerificationException: Operation could destabilize the runtime.
at HandlebarsDotNet.StringUtils.Substring.SplitEnumerator.MoveNext()
at HandlebarsDotNet.Collections.ExtendedEnumerator`2.PerformIteration()
at HandlebarsDotNet.Collections.ExtendedEnumerator`2..ctor(TEnumerator enumerator)
at HandlebarsDotNet.Collections.ExtendedEnumerator`1.Create[TEnumerator](TEnumerator enumerator)
at HandlebarsDotNet.PathStructure.PathInfo.Parse(String path)
at HandlebarsDotNet.PathStructure.PathInfoStore.&lt;&gt;c.&lt;.cctor&gt;b__6_1(String pathString)
at HandlebarsDotNet.Runtime.DeferredValue`2.get_Value()
at HandlebarsDotNet.PathStructure.PathInfoStore.GetOrAdd(String path)
at HandlebarsDotNet.PathStructure.PathInfo.op_Implicit(String path)
at HandlebarsDotNet.Helpers.BlockHelpers.WithBlockHelperDescriptor..ctor()
at HandlebarsDotNet.Features.BuildInHelpersFeature..cctor()
--- End of inner exception stack trace ---
at HandlebarsDotNet.Features.BuildInHelpersFeature..ctor()
at HandlebarsDotNet.Features.BuildInHelpersFeatureFactory.CreateFeature()
at HandlebarsDotNet.HandlebarsConfigurationAdapter.&lt;&gt;c.&lt;.ctor&gt;b__1_0(IFeatureFactory o)
at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
at System.Linq.OrderedEnumerable`1.&lt;GetEnumerator&gt;d__1.MoveNext()
at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
at HandlebarsDotNet.HandlebarsConfigurationAdapter..ctor(HandlebarsConfiguration configuration)
at HandlebarsDotNet.HandlebarsEnvironment.Compile(TextReader template)
at HandlebarsDotNet.HandlebarsEnvironment.Compile(String template)
at HandlebarsDotNet.Handlebars.Compile(String template)
```

I wonder if Handlebars can be somehow configured not to load builtin helpers?
