### ISSUE TITLE
Sequence contains more than one element

### ISSUE THREAD

**Issue by johnknoop** [rexm/Handlebars.Net#301]
I have a Handlebars template that I've verified works both on http://tryhandlebarsjs.com/ and using the Handlebars Preview extension in VS Code.

However, I get this exception when compiling it with Handlebars.Net:

```csharp
System.InvalidOperationException: Sequence contains more than one element
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at HandlebarsDotNet.Compiler.IteratorBlockAccumulatorContext.IsClosingElement(Expression item)
   at HandlebarsDotNet.Compiler.BlockAccumulator.AccumulateBlock(IEnumerator`1 enumerator, BlockAccumulatorContext context)
   at HandlebarsDotNet.Compiler.BlockAccumulator.AccumulateBlock(IEnumerator`1 enumerator, BlockAccumulatorContext context)
   at HandlebarsDotNet.Compiler.BlockAccumulator.AccumulateBlock(IEnumerator`1 enumerator, BlockAccumulatorContext context)
   at HandlebarsDotNet.Compiler.BlockAccumulator.ConvertTokens(IEnumerable`1 sequence)+MoveNext()
   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at HandlebarsDotNet.Compiler.ExpressionBuilder.ConvertTokensToExpressions(IEnumerable`1 tokens)
   at HandlebarsDotNet.Compiler.HandlebarsCompiler.Compile(TextReader source)
   at HandlebarsDotNet.Handlebars.HandlebarsEnvironment.Compile(String template)
```

This is the template:

```handlebars
<div>
{{#each Items as |item|}}
	<span>
	{{#if item.HasVariants}}
		<strong>
		{{#each item.Variants as |variant|}}
			<i>{{variant.Code}}</i>
		{{/each}}
		</strong>
	{{else}}
		<strong>
		{{item.Code}}
		</strong>
	{{/if}}
	</span>
{{/each}}
</div>
```

Any ideas?

**Comment by rexm** [comment]
The `as |alias|` syntax isn't supported yet.

**Comment by johnknoop** [comment]
I see. Thanks!
