### ISSUE TITLE
Please report betters errors (context) when having mistakes in the template

### ISSUE THREAD

**Issue by 304NotModified** [rexm/Handlebars.Net#314]
## Example 1

`{{#File}}` (mistake, should be `{{File}}`

gives:
```
HandlebarsDotNet.HandlebarsCompilerException: Reached end of template before block expression '' was closed
    at HandlebarsDotNet.Compiler.BlockAccumulator.AccumulateBlock(IEnumerator`1 enumerator, BlockAccumulatorContext context)
   at HandlebarsDotNet.Compiler.BlockAccumulator.<ConvertTokens>d__3.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at HandlebarsDotNet.Compiler.BlockAccumulator.Accumulate(IEnumerable`1 tokens, HandlebarsConfiguration configuration)
   at HandlebarsDotNet.Compiler.ExpressionBuilder.ConvertTokensToExpressions(IEnumerable`1 tokens)
   at HandlebarsDotNet.Compiler.HandlebarsCompiler.Compile(TextReader source)
   at HandlebarsDotNet.Handlebars.HandlebarsEnvironment.Compile(String template)
   at HandlebarsDotNet.Handlebars.Compile(String template)
```

## Example 2

`{{File}}}`

```
HandlebarsDotNet.HandlebarsCompilerException: Starting and ending handlebars do not match
    at HandlebarsDotNet.Compiler.ExpressionScopeConverter.<ConvertTokens>d__2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at HandlebarsDotNet.Compiler.ExpressionScopeConverter.Convert(IEnumerable`1 sequence)
   at HandlebarsDotNet.Compiler.ExpressionBuilder.ConvertTokensToExpressions(IEnumerable`1 tokens)
   at HandlebarsDotNet.Compiler.HandlebarsCompiler.Compile(TextReader source)
   at HandlebarsDotNet.Handlebars.HandlebarsEnvironment.Compile(String template)
   at HandlebarsDotNet.Handlebars.Compile(String template)
```

Missing line / column numbers

## Example 3 

`{{#if !File}} {{/if}}`  (wrong `!`)

```
HandlebarsDotNet.HandlebarsCompilerException: An unhandled exception occurred while trying to compile the template ---> HandlebarsDotNet.HandlebarsCompilerException: An unhandled exception occurred while trying to compile the template ---> System.ArgumentException: must be reducible node
    at System.Linq.Expressions.Expression.VisitChildren(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.VisitExtension(Expression node)
   at System.Linq.Expressions.Expression.Accept(ExpressionVisitor visitor)
   at HandlebarsDotNet.Compiler.HandlebarsExpressionVisitor.Visit(Expression exp)
   at HandlebarsDotNet.Compiler.HandlebarsExpressionVisitor.VisitBoolishExpression(BoolishExpression bex)
   at HandlebarsDotNet.Compiler.HandlebarsExpressionVisitor.Visit(Expression exp)
   at System.Linq.Expressions.ExpressionVisitor.VisitConditional(ConditionalExpression node)
   at System.Linq.Expressions.ConditionalExpression.Accept(ExpressionVisitor visitor)
   at HandlebarsDotNet.Compiler.HandlebarsExpressionVisitor.Visit(Expression exp)
   at System.Linq.Expressions.ExpressionVisitor.VisitBlock(BlockExpression node)
   at System.Linq.Expressions.BlockExpression.Accept(ExpressionVisitor visitor)
   at HandlebarsDotNet.Compiler.HandlebarsExpressionVisitor.Visit(Expression exp)
   at HandlebarsDotNet.Compiler.FunctionBuilder.Compile(IEnumerable`1 expressions, Expression parentContext, String templatePath)
--- End of inner exception stack trace ---
    at HandlebarsDotNet.Compiler.FunctionBuilder.Compile(IEnumerable`1 expressions, Expression parentContext, String templatePath)
   at HandlebarsDotNet.Compiler.FunctionBuilder.Compile(IEnumerable`1 expressions, String templatePath)
--- End of inner exception stack trace ---
    at HandlebarsDotNet.Compiler.FunctionBuilder.Compile(IEnumerable`1 expressions, String templatePath)
   at HandlebarsDotNet.Compiler.HandlebarsCompiler.Compile(TextReader source)
   at HandlebarsDotNet.Handlebars.HandlebarsEnvironment.Compile(String template)
   at HandlebarsDotNet.Handlebars.Compile(String template)
```

**Comment by 304NotModified** [comment]
Another example is here: https://github.com/rexm/Handlebars.Net/issues/301

**Comment by 304NotModified** [comment]
Related error issue here: https://github.com/rexm/Handlebars.Net/issues/306

**Comment by rexm** [comment]
PR welcome

**Comment by 304NotModified** [comment]
Are the row and column numbers now tracked after compiling? Where could I find them?

**Comment by rexm** [comment]
They are not. This has been on the roadmap for v2 for a few years and requires a refactoring at every layer in the compiler - no small amount of work, but fairly well understood.

**Comment by 304NotModified** [comment]
@rexm can I go from `Token` to the original source? If not, could I add that?

**Comment by rexm** [comment]
That would be the first step, each token would need to be reversible. In some cases during that stage some meaningless white space is thrown away so that would need to be accounted for.

**Comment by 304NotModified** [comment]
OK, for error messages the meaningless white space isn't really a problem I guess ;)

**Comment by 304NotModified** [comment]
> That would be the first step, each token would need to be reversible. In some cases during that stage some meaningless white space is thrown away so that would need to be accounted for.

something like this? https://github.com/rexm/Handlebars.Net/pull/316

**Comment by rexm** [comment]
I mention it because if your goal is reporting the row and column, it may be slightly off based on that.

**Comment by 304NotModified** [comment]
yes, row and column would be great, but I think that's the hard for now.

So therefor im also fine with printing the value which is error. 

e.g.

`{{#File}}` could give, `{{#File}} is not closed`

**Comment by statler** [comment]
Just following on from this @304NotModified or @rexm what is the best context that can be **easily** identified to provide more informative feedback to users. In my case, I have users defining their own templates which are later used in the system to generate HTML for fields. When the template is wrong, I would like to provide as much information as I can to help pinpoint the issue rather than something like "Starting and ending handlebars do not match". 

I understand that precision will require significant re-engineering, but am curious what **could** be done given current architecture.
