### ISSUE TITLE
"Error: Starting and ending handlebars do not match" When there are three adjacent ending braces.

### ISSUE THREAD

**Issue by Ellaluo** [rexm/Handlebars.Net#346]
I was doing:
 
```csharp
_handlebars.Compile("{\"key\": {{value}}}");
```

but got:

```
 ERROR Request for: /api/path , Method: POST , Queries: ?environment=production , Error: Starting and ending handlebars do not match , Unhandled Exception occured:    at HandlebarsDotNet.Compiler.ExpressionScopeConverter.ConvertTokens(IEnumerable`1 sequence)+MoveNext()
   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at HandlebarsDotNet.Compiler.ExpressionBuilder.ConvertTokensToExpressions(IEnumerable`1 tokens)
   at HandlebarsDotNet.Compiler.HandlebarsCompiler.Compile(TextReader source)
   at HandlebarsDotNet.Handlebars.HandlebarsEnvironment.Compile(String template)
```

If I added _a blank space before the last brace_, like this:

```csharp
_handlebars.Compile("{\"key\": {{value}} }");
```

then all work well.

Is this a but or I have missed out anything?

**Comment by rexm** [comment]
The “triple-stash”: {{{ expression }}} has special meaning in the handlebars language - it means render the expression without escaping HTML characters. In your example you opened the expression with a double but ended it with a triple, so it correctly identified they do not match. Putting a space ensures the compiler recognizes the third } as a separate entity and not part of the closing expression.
